version: '3.8'

services:
  frontend:
    build: ./frontend
    command: npm run build
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - frontend

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
