services:
- type: web
  name: my-backend
  runtime: docker
  dockerfilePath: ./backend/Dockerfile
  envVars:
      - key: MONGO_URI
        value: mongodb+srv://talsi:Talsi201095@top-tech.t0e87hw.mongodb.net/?retryWrites=true&w=majority&appName=Top-Tech
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: shma_israel_hashem_elokeinu_hashem_echad
      - key: GMAIL_USER
        value: tal5566172@gmail.com
      - key: GMAIL_PASS
      - value: oqvmaeweiuzbnhqh

- type: static
  name: my-frontend
  buildCommand: npm run build
  staticPublishPath: ./dist
  rootDir: frontend